version: 0.0
os: linux

files:
  - source: /client
    destination: /home/ubuntu/bmart-7/client/build
permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_client_deploy.sh
      runas: ubuntu
